version: "1.0"
info:
  model: int-scaffold
packages:
- name: FR_STT_AccountManagementProject
  gitServerName: staillanibm
  gitUrl: https://github.com/staillanibm
  gitUsername: staillanibm
  gitBranch: main
- name: WmJDBCAdapter
  version: 10.3.0.0.34
  wpmServer: https://packages.webmethods.io
  wpmRegistry: licensed
services:
- serviceName: project.fr_stt_accountmanagement.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections:contabo_sttlab_eu
  packages:
  - name: FR_STT_AccountManagementProject
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
- serviceName: project.fr_stt_accountmanagement.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.operations.actions:insertAccount
  packages:
  - name: FR_STT_AccountManagementProject
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
- serviceName: project.fr_stt_accountmanagement.integrations:createAccount
  packages:
  - name: FR_STT_AccountManagementProject
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
configurationVariables:
  ? artConnection.FR_STT_AccountManagementProject.project.fr_stt_accountmanagement.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.contabo_sttlab_eu.connectionManagerSettings.minimumPoolSize
  : "1"
  ? artConnection.FR_STT_AccountManagementProject.project.fr_stt_accountmanagement.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.contabo_sttlab_eu.connectionSettings.networkProtocol
  : ""
  ? artConnection.FR_STT_AccountManagementProject.project.fr_stt_accountmanagement.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.contabo_sttlab_eu.connectionSettings.datasourceClass
  : com.wm.dd.jdbcx.sqlserver.SQLServerDataSource
  ? artConnection.FR_STT_AccountManagementProject.project.fr_stt_accountmanagement.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.contabo_sttlab_eu.connectionManagerSettings.startupRetryCount
  : "0"
  ? artConnection.FR_STT_AccountManagementProject.project.fr_stt_accountmanagement.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.contabo_sttlab_eu.connectionManagerSettings.poolIncrementSize
  : "1"
  ? artConnection.FR_STT_AccountManagementProject.project.fr_stt_accountmanagement.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.contabo_sttlab_eu.connectionSettings.trustStore
  : ""
  ? artConnection.FR_STT_AccountManagementProject.project.fr_stt_accountmanagement.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.contabo_sttlab_eu.connectionSettings.driverType
  : Progress® DataDirect®
  ? artConnection.FR_STT_AccountManagementProject.project.fr_stt_accountmanagement.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.contabo_sttlab_eu.connectionManagerSettings.startupBackoffSecs
  : "10"
  ? artConnection.FR_STT_AccountManagementProject.project.fr_stt_accountmanagement.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.contabo_sttlab_eu.connectionSettings.dbType
  : MSSQL
  ? artConnection.FR_STT_AccountManagementProject.project.fr_stt_accountmanagement.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.contabo_sttlab_eu.connectionSettings.portNumber
  : "1433"
  ? artConnection.FR_STT_AccountManagementProject.project.fr_stt_accountmanagement.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.contabo_sttlab_eu.connectionSettings.password
  : "{AES}zxtjDVPnPMSWIVvNbTQB+H9awpHAyfXYCxLWEZQhnoE="
  ? artConnection.FR_STT_AccountManagementProject.project.fr_stt_accountmanagement.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.contabo_sttlab_eu.connectionManagerSettings.heartBeatInterval
  : "0"
  ? artConnection.FR_STT_AccountManagementProject.project.fr_stt_accountmanagement.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.contabo_sttlab_eu.connectionSettings.otherProperties
  : loginTimeout=60;
  ? artConnection.FR_STT_AccountManagementProject.project.fr_stt_accountmanagement.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.contabo_sttlab_eu.connectionManagerSettings.blockingTimeout
  : "1000"
  ? artConnection.FR_STT_AccountManagementProject.project.fr_stt_accountmanagement.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.contabo_sttlab_eu.connectionSettings.databaseName
  : sandbox
  ? artConnection.FR_STT_AccountManagementProject.project.fr_stt_accountmanagement.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.contabo_sttlab_eu.connectionManagerSettings.expireTimeout
  : "1000"
  ? artConnection.FR_STT_AccountManagementProject.project.fr_stt_accountmanagement.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.contabo_sttlab_eu.connectionSettings.user
  : sa
  ? artConnection.FR_STT_AccountManagementProject.project.fr_stt_accountmanagement.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.contabo_sttlab_eu.connectionSettings.serverName
  : contabo.sttlab.eu
  ? artConnection.FR_STT_AccountManagementProject.project.fr_stt_accountmanagement.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.contabo_sttlab_eu.connectionManagerSettings.maximumPoolSize
  : "10"
  ? artConnection.FR_STT_AccountManagementProject.project.fr_stt_accountmanagement.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.contabo_sttlab_eu.connectionSettings.transactionType
  : NO_TRANSACTION
  ? artConnection.FR_STT_AccountManagementProject.project.fr_stt_accountmanagement.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.contabo_sttlab_eu.connectionEnabled
  : "false"
  ? artConnection.FR_STT_AccountManagementProject.project.fr_stt_accountmanagement.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.contabo_sttlab_eu.connectionManagerSettings.poolable
  : "true"
  ? artConnection.FR_STT_AccountManagementProject.project.fr_stt_accountmanagement.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.contabo_sttlab_eu.connectionSettings.keyStore
  : ""
